// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.4
// source: hotelpb/hotel.proto

package hotelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteHotelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to By:
	//
	//	*DeleteHotelRequest_Id
	//	*DeleteHotelRequest_OwnerId
	By isDeleteHotelRequest_By `protobuf_oneof:"by"`
}

func (x *DeleteHotelRequest) Reset() {
	*x = DeleteHotelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelpb_hotel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHotelRequest) ProtoMessage() {}

func (x *DeleteHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotelpb_hotel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHotelRequest.ProtoReflect.Descriptor instead.
func (*DeleteHotelRequest) Descriptor() ([]byte, []int) {
	return file_hotelpb_hotel_proto_rawDescGZIP(), []int{0}
}

func (m *DeleteHotelRequest) GetBy() isDeleteHotelRequest_By {
	if m != nil {
		return m.By
	}
	return nil
}

func (x *DeleteHotelRequest) GetId() string {
	if x, ok := x.GetBy().(*DeleteHotelRequest_Id); ok {
		return x.Id
	}
	return ""
}

func (x *DeleteHotelRequest) GetOwnerId() string {
	if x, ok := x.GetBy().(*DeleteHotelRequest_OwnerId); ok {
		return x.OwnerId
	}
	return ""
}

type isDeleteHotelRequest_By interface {
	isDeleteHotelRequest_By()
}

type DeleteHotelRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type DeleteHotelRequest_OwnerId struct {
	OwnerId string `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3,oneof"`
}

func (*DeleteHotelRequest_Id) isDeleteHotelRequest_By() {}

func (*DeleteHotelRequest_OwnerId) isDeleteHotelRequest_By() {}

type GetHotelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetHotelsRequest) Reset() {
	*x = GetHotelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelpb_hotel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHotelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelsRequest) ProtoMessage() {}

func (x *GetHotelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotelpb_hotel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelsRequest.ProtoReflect.Descriptor instead.
func (*GetHotelsRequest) Descriptor() ([]byte, []int) {
	return file_hotelpb_hotel_proto_rawDescGZIP(), []int{1}
}

func (x *GetHotelsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetHotelsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Hotels struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Hotel `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *Hotels) Reset() {
	*x = Hotels{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelpb_hotel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hotels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hotels) ProtoMessage() {}

func (x *Hotels) ProtoReflect() protoreflect.Message {
	mi := &file_hotelpb_hotel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hotels.ProtoReflect.Descriptor instead.
func (*Hotels) Descriptor() ([]byte, []int) {
	return file_hotelpb_hotel_proto_rawDescGZIP(), []int{2}
}

func (x *Hotels) GetList() []*Hotel {
	if x != nil {
		return x.List
	}
	return nil
}

type GetHotelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to By:
	//
	//	*GetHotelRequest_Id
	//	*GetHotelRequest_AdminId
	By isGetHotelRequest_By `protobuf_oneof:"by"`
}

func (x *GetHotelRequest) Reset() {
	*x = GetHotelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelpb_hotel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelRequest) ProtoMessage() {}

func (x *GetHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotelpb_hotel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelRequest.ProtoReflect.Descriptor instead.
func (*GetHotelRequest) Descriptor() ([]byte, []int) {
	return file_hotelpb_hotel_proto_rawDescGZIP(), []int{3}
}

func (m *GetHotelRequest) GetBy() isGetHotelRequest_By {
	if m != nil {
		return m.By
	}
	return nil
}

func (x *GetHotelRequest) GetId() string {
	if x, ok := x.GetBy().(*GetHotelRequest_Id); ok {
		return x.Id
	}
	return ""
}

func (x *GetHotelRequest) GetAdminId() string {
	if x, ok := x.GetBy().(*GetHotelRequest_AdminId); ok {
		return x.AdminId
	}
	return ""
}

type isGetHotelRequest_By interface {
	isGetHotelRequest_By()
}

type GetHotelRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetHotelRequest_AdminId struct {
	AdminId string `protobuf:"bytes,2,opt,name=admin_id,json=adminId,proto3,oneof"`
}

func (*GetHotelRequest_Id) isGetHotelRequest_By() {}

func (*GetHotelRequest_AdminId) isGetHotelRequest_By() {}

type Hotel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Star    uint32 `protobuf:"varint,3,opt,name=star,proto3" json:"star,omitempty"`
	OwnerId string `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	AdminId string `protobuf:"bytes,5,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Address string `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Budget  int32  `protobuf:"varint,7,opt,name=budget,proto3" json:"budget,omitempty"`
}

func (x *Hotel) Reset() {
	*x = Hotel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelpb_hotel_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hotel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hotel) ProtoMessage() {}

func (x *Hotel) ProtoReflect() protoreflect.Message {
	mi := &file_hotelpb_hotel_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hotel.ProtoReflect.Descriptor instead.
func (*Hotel) Descriptor() ([]byte, []int) {
	return file_hotelpb_hotel_proto_rawDescGZIP(), []int{4}
}

func (x *Hotel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hotel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hotel) GetStar() uint32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *Hotel) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Hotel) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *Hotel) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Hotel) GetBudget() int32 {
	if x != nil {
		return x.Budget
	}
	return 0
}

type RegisterHotelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Star    uint32 `protobuf:"varint,2,opt,name=star,proto3" json:"star,omitempty"`
	OwnerId string `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	AdminId string `protobuf:"bytes,4,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	Address string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Budget  int32  `protobuf:"varint,6,opt,name=budget,proto3" json:"budget,omitempty"`
}

func (x *RegisterHotelRequest) Reset() {
	*x = RegisterHotelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hotelpb_hotel_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHotelRequest) ProtoMessage() {}

func (x *RegisterHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotelpb_hotel_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHotelRequest.ProtoReflect.Descriptor instead.
func (*RegisterHotelRequest) Descriptor() ([]byte, []int) {
	return file_hotelpb_hotel_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterHotelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterHotelRequest) GetStar() uint32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *RegisterHotelRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *RegisterHotelRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

func (x *RegisterHotelRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterHotelRequest) GetBudget() int32 {
	if x != nil {
		return x.Budget
	}
	return 0
}

var File_hotelpb_hotel_proto protoreflect.FileDescriptor

var file_hotelpb_hotel_proto_rawDesc = []byte{
	0x0a, 0x13, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x70, 0x62, 0x2f, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x70, 0x62, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x12, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x42, 0x04, 0x0a, 0x02, 0x62, 0x79, 0x22, 0x3c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74,
	0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0x2c, 0x0a, 0x06, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x12, 0x22,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x68,
	0x6f, 0x74, 0x65, 0x6c, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x22, 0x46, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x49, 0x64, 0x42, 0x04, 0x0a, 0x02, 0x62, 0x79, 0x22, 0xa7, 0x01, 0x0a, 0x05, 0x48,
	0x6f, 0x74, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x74, 0x61, 0x72, 0x12, 0x19, 0x0a, 0x08,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62, 0x75,
	0x64, 0x67, 0x65, 0x74, 0x22, 0xa6, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x73, 0x74, 0x61, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x32, 0xb0, 0x02,
	0x0a, 0x0c, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e,
	0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x12,
	0x1d, 0x2e, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e,
	0x2e, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x12, 0x34,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x12, 0x18, 0x2e, 0x68, 0x6f, 0x74,
	0x65, 0x6c, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x70, 0x62, 0x2e, 0x48,
	0x6f, 0x74, 0x65, 0x6c, 0x12, 0x2d, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x6f,
	0x74, 0x65, 0x6c, 0x12, 0x0e, 0x2e, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x70, 0x62, 0x2e, 0x48, 0x6f,
	0x74, 0x65, 0x6c, 0x1a, 0x0e, 0x2e, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x70, 0x62, 0x2e, 0x48, 0x6f,
	0x74, 0x65, 0x6c, 0x12, 0x42, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x6f, 0x74,
	0x65, 0x6c, 0x12, 0x1b, 0x2e, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x37, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x48, 0x6f,
	0x74, 0x65, 0x6c, 0x73, 0x12, 0x19, 0x2e, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0f, 0x2e, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x70, 0x62, 0x2e, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73,
	0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70,
	0x75, 0x6c, 0x61, 0x74, 0x6e, 0x61, 0x7a, 0x61, 0x72, 0x6f, 0x76, 0x2f, 0x68, 0x6f, 0x74, 0x65,
	0x6c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hotelpb_hotel_proto_rawDescOnce sync.Once
	file_hotelpb_hotel_proto_rawDescData = file_hotelpb_hotel_proto_rawDesc
)

func file_hotelpb_hotel_proto_rawDescGZIP() []byte {
	file_hotelpb_hotel_proto_rawDescOnce.Do(func() {
		file_hotelpb_hotel_proto_rawDescData = protoimpl.X.CompressGZIP(file_hotelpb_hotel_proto_rawDescData)
	})
	return file_hotelpb_hotel_proto_rawDescData
}

var file_hotelpb_hotel_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_hotelpb_hotel_proto_goTypes = []interface{}{
	(*DeleteHotelRequest)(nil),   // 0: hotelpb.DeleteHotelRequest
	(*GetHotelsRequest)(nil),     // 1: hotelpb.GetHotelsRequest
	(*Hotels)(nil),               // 2: hotelpb.Hotels
	(*GetHotelRequest)(nil),      // 3: hotelpb.GetHotelRequest
	(*Hotel)(nil),                // 4: hotelpb.Hotel
	(*RegisterHotelRequest)(nil), // 5: hotelpb.RegisterHotelRequest
	(*emptypb.Empty)(nil),        // 6: google.protobuf.Empty
}
var file_hotelpb_hotel_proto_depIdxs = []int32{
	4, // 0: hotelpb.Hotels.list:type_name -> hotelpb.Hotel
	5, // 1: hotelpb.HotelService.RegisterHotel:input_type -> hotelpb.RegisterHotelRequest
	3, // 2: hotelpb.HotelService.GetHotel:input_type -> hotelpb.GetHotelRequest
	4, // 3: hotelpb.HotelService.UpdateHotel:input_type -> hotelpb.Hotel
	0, // 4: hotelpb.HotelService.DeleteHotel:input_type -> hotelpb.DeleteHotelRequest
	1, // 5: hotelpb.HotelService.GetHotels:input_type -> hotelpb.GetHotelsRequest
	4, // 6: hotelpb.HotelService.RegisterHotel:output_type -> hotelpb.Hotel
	4, // 7: hotelpb.HotelService.GetHotel:output_type -> hotelpb.Hotel
	4, // 8: hotelpb.HotelService.UpdateHotel:output_type -> hotelpb.Hotel
	6, // 9: hotelpb.HotelService.DeleteHotel:output_type -> google.protobuf.Empty
	2, // 10: hotelpb.HotelService.GetHotels:output_type -> hotelpb.Hotels
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hotelpb_hotel_proto_init() }
func file_hotelpb_hotel_proto_init() {
	if File_hotelpb_hotel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hotelpb_hotel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteHotelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotelpb_hotel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHotelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotelpb_hotel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hotels); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotelpb_hotel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHotelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotelpb_hotel_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hotel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hotelpb_hotel_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterHotelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_hotelpb_hotel_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*DeleteHotelRequest_Id)(nil),
		(*DeleteHotelRequest_OwnerId)(nil),
	}
	file_hotelpb_hotel_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*GetHotelRequest_Id)(nil),
		(*GetHotelRequest_AdminId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hotelpb_hotel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hotelpb_hotel_proto_goTypes,
		DependencyIndexes: file_hotelpb_hotel_proto_depIdxs,
		MessageInfos:      file_hotelpb_hotel_proto_msgTypes,
	}.Build()
	File_hotelpb_hotel_proto = out.File
	file_hotelpb_hotel_proto_rawDesc = nil
	file_hotelpb_hotel_proto_goTypes = nil
	file_hotelpb_hotel_proto_depIdxs = nil
}
